/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    All: typeof import('./pages/All.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    Favorites: typeof import('./pages/Favorites.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
